// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/api/logout.ts";
import * as $4 from "./routes/api/rooms.ts";
import * as $5 from "./routes/api/signup.ts";
import * as $6 from "./routes/api/ws.ts";
import * as $7 from "./routes/index.tsx";
import * as $8 from "./routes/room/[roomId].tsx";
import * as $$0 from "./islands/PokerGame.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/api/logout.ts": $3,
    "./routes/api/rooms.ts": $4,
    "./routes/api/signup.ts": $5,
    "./routes/api/ws.ts": $6,
    "./routes/index.tsx": $7,
    "./routes/room/[roomId].tsx": $8,
  },
  islands: {
    "./islands/PokerGame.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
